[package]
name = "vegetables_and_hummus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.9"
itertools = "0.12"
nalgebra="0.32"
rand = "0.8"